### ISSUE TITLE
I2C_Demo fails to compile

### ISSUE THREAD

**Issue by pictorf** [bitbank2/ssd1327#5]
I'm using a MKR1000, and tried for UNO aswell.
I made the modifications indicated in previous issue #0afd522, both in I2C_Demo.ino and in ssd1327.cpp but got a this error message : 
`
C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp: In function 'void oledWrite(unsigned char*, int)':

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:219:39: error: invalid conversion from 'int' to 'BBI2C* {aka mybbi2c*}' [-fpermissive]

        I2CWrite(oled_addr, pData, iLen);

                                       ^

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:219:39: error: invalid conversion from 'unsigned char*' to 'uint8_t {aka unsigned char}' [-fpermissive]

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:219:39: error: invalid conversion from 'int' to 'uint8_t* {aka unsigned char*}' [-fpermissive]

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:219:39: error: too few arguments to function 'int I2CWrite(BBI2C*, uint8_t, uint8_t*, int)'

In file included from C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:43:0:

C:\Users\xxx\Documents\Arduino\libraries\BitBang_I2C\src/BitBang_I2C.h:79:5: note: declared here

 int I2CWrite(BBI2C *pI2C, uint8_t iAddr, uint8_t *pData, int iLen);

     ^~~~~~~~

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp: In function 'void ssd1327Init(int, int, int, int, int, int, int32_t)':

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:379:27: error: invalid conversion from 'int' to 'BBI2C* {aka mybbi2c*}' [-fpermissive]

   I2CInit(sda, scl, iSpeed);

                           ^

C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:379:27: error: too many arguments to function 'void I2CInit(BBI2C*, uint32_t)'

In file included from C:\Users\xxx\Documents\Arduino\libraries\SSD1327\src\ssd1327.cpp:43:0:

C:\Users\xxx\Documents\Arduino\libraries\BitBang_I2C\src/BitBang_I2C.h:97:6: note: declared here

 void I2CInit(BBI2C *pI2C, uint32_t iClock);

      ^~~~~~~

exit status 1
`

**Comment by thijstriemstra** [comment]
same on esp32 (without modifications), example doesn't compile.

**Comment by rankinjonathan** [comment]
I also cannot get it to compile with Adafruit Feather M0

**Comment by jorisbertomeu** [comment]
Hey guys, FYI, it works with BitBang_I2C v1.3.0 👍

**Comment by kwaggarsa** [comment]
I am trying to get this to work on a Arduino nano V3, so i wired the A0 and A1, VCC and Gnd, set the jumper to select I2C but no Luck, which pins did you use to get it working ? Even added pullup resistors.
